### ISSUE TITLE
Cannot read property 'abstract' of null

### ISSUE THREAD

**Issue by gimox** [ncuillery/angular-breadcrumb#81]
i receive this error when settings nested view:

```javascript
.state('dashboard', {
        url          : '/dashboard',
        templateUrl  : 'app/project/tmpl/dashboard.tmpl.html',
        abstract: true,
        ncyBreadcrumb: {
          label: 'Dashboard'
        }
      })

      .state('dashboard.home', {
        url : '',
        templateUrl: 'app/project/tmpl/dashboard.home.tmpl.html',
        ncyBreadcrumb: {
          label:'test'
        }
      });
```

if add <div ncy-breadcrumb></div> in dashboard.home.tmpl.html i receive this error:

```
TypeError: Cannot read property 'abstract' of null
    at $get.$$addStateInChain (http://localhost:3000/bower_components/angular-breadcrumb/release/angular-breadcrumb.js:68:22)
    at Object.$get.getStatesChain (http://localhost:3000/bower_components/angular-breadcrumb/release/angular-breadcrumb.js:126:21)
    at link.post.renderBreadcrumb (http://localhost:3000/bower_components/angular-breadcrumb/release/angular-breadcrumb.js:205:47)
    at postLink (http://localhost:3000/bower_components/angular-breadcrumb/release/angular-breadcrumb.js:223:17)
    at http://localhost:3000/bower_components/angular/angular.js:8252:44
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8258:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7768:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7117:13)
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:6996:30)
    at compile (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3905:9) <ol class="breadcrumb ng-scope ng-isolate-scope" ncy-breadcrumb="">angular.js:11655 (anonymous function)angular.js:8596 $getangular.js:8260 invokeLinkFn
..
```

i have try different config but same error...

help!

**Comment by ncuillery** [comment]
Nothing seems wrong in your config...

Please can you provide the versions of:
- angular
- ui-router
- angular-breadcrumb

It could be helpful if you can reproduce the bug in a plunker too. You can fork [this one](http://plnkr.co/edit/O8oOgnvcJ57k97f1fWRW)

**Comment by gimox** [comment]
"angular": "~1.3.4",
 "angular-breadcrumb": "~0.3.3",
"angular-ui-router": "~0.2.13",

thanks

**Comment by tomasz-galazka** [comment]
I came across the same error "Cannot read property 'abstract' of null"
Did you fix it?

**Comment by gimox** [comment]
no! i can not use the breadcrum until fix it!

**Comment by tlode** [comment]
Could it be that this is just a configuration problem? I've had copied this example from the API Reference

```
$breadcrumbProvider.setOptions({
      prefixStateName: 'home',
      template: 'bootstrap2'
});
```

without having the `home` state. Changing this to some known state has helped fix the problem.

**Comment by ncuillery** [comment]
@gimox @tomasz-galazka Did you configure the `breadcrumbProvider` and define an non-existing or abstract state name in the key `prefixStateName` ? 

It could happen if you have copied-pasted the example from the API reference, as @tlode suggested.

**Comment by gimox** [comment]
try with default config and check existing state. no work.
